/** Official Sindh districts for domicile and residence fields. */
export const SINDH_DISTRICTS = [
  'Badin',
  'Dadu',
  'Ghotki',
  'Hyderabad',
  'Jacobabad',
  'Jamshoro',
  'Karachi Central',
  'Karachi East',
  'Karachi Keamari',
  'Karachi Korangi',
  'Karachi Malir',
  'Karachi South',
  'Karachi West',
  'Kashmore',
  'Khairpur',
  'Larkana',
  'Matiari',
  'Mirpur Khas',
  'Naushahro Feroze',
  'Qambar Shahdadkot',
  'Sanghar',
  'Shaheed Benazirabad',
  'Shikarpur',
  'Sujawal',
  'Sukkur',
  'Tando Allahyar',
  'Tando Muhammad Khan',
  'Tharparkar',
  'Thatta',
  'Umerkot',
] as const;

export type SindhDistrict = (typeof SINDH_DISTRICTS)[number];
